/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CV Assistant
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const AppControllerGetHello200 = zod.object({
  "message": zod.string().optional()
})

export type AppControllerGetHello200 = zod.input<typeof AppControllerGetHello200>;
