/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CV Assistant
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const AuthControllerSignUpBody = zod.object({
  "email": zod.string(),
  "firstName": zod.string().optional(),
  "lastName": zod.string().optional(),
  "avatarUrl": zod.string().optional(),
  "role": zod.string(),
  "password": zod.string()
})

export type AuthControllerSignUpBody = zod.input<typeof AuthControllerSignUpBody>;
