/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * CV Assistant
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const LoginDto = zod.object({
  "email": zod.string(),
  "password": zod.string()
})

export type LoginDto = zod.input<typeof LoginDto>;
