export const RESUME_A4_WIDTH_PX = 794;
export const RESUME_A4_HEIGHT_PX = 1123;
export const RESUME_PREVIEW_PADDING_PX = 24;

export const RESUME_PDF_SCALE = 0.75;

export const pxToPt = (value: number) => value * RESUME_PDF_SCALE;

export const resumeConstructorLayout = {
  classic: {
    sidebarWidthPx: 176,
    sidebarPaddingHorizontalPx: 20,
    sidebarPaddingVerticalPx: 24,
    contentPaddingHorizontalPx: 24,
    contentPaddingVerticalPx: 24,
    nameFontSizePx: 20,
    titleFontSizePx: 9.5,
    titleLetterSpacingPx: 1.2,
    contactTopMarginPx: 14,
    contactFontSizePx: 8.2,
    sectionTopMarginPx: 16,
    sectionTitleFontSizePx: 9,
    sectionTitleLetterSpacingPx: 1.1,
    sectionTitleBottomMarginPx: 6,
    paragraphFontSizePx: 9.2,
    bulletTopMarginPx: 2,
    bulletRowBottomMarginPx: 4,
    bulletWidthPx: 9,
    bulletFontSizePx: 9,
    bulletPaddingTopPx: 0.5,
    skillChipTopMarginPx: 2,
    skillChipBorderWidthPx: 1,
    skillChipHorizontalPaddingPx: 7,
    skillChipVerticalPaddingPx: 4,
    skillChipRightMarginPx: 5,
    skillChipBottomMarginPx: 5,
    skillChipFontSizePx: 8.1,
    sectionBottomMarginPx: 18,
    experienceItemBottomMarginPx: 11,
    roleRowBottomMarginPx: 3,
    roleTitleFontSizePx: 11.2,
    companyFontSizePx: 9.2,
    companyTopMarginPx: 1,
    roleMetaFontSizePx: 8.1,
    roleMetaTopMarginPx: 2,
    educationItemBottomMarginPx: 10,
    educationTitleFontSizePx: 9.5,
    educationMetaFontSizePx: 8.1,
    educationMetaTopMarginPx: 2,
    dividerHeightPx: 1,
    dividerVerticalMarginPx: 10,
  },
  modern: {
    headerHorizontalPaddingPx: 24,
    headerVerticalPaddingPx: 24,
    headerGapPx: 0,
    titleFontSizePx: 22,
    titleLetterSpacingPx: -0.5,
    titleTopMarginPx: 4,
    subtitleFontSizePx: 9.8,
    subtitleLetterSpacingPx: 1.3,
    contactGapPx: 12,
    contactChipHorizontalPaddingPx: 0,
    contactChipVerticalPaddingPx: 0,
    contactChipLeftMarginPx: 0,
    contactChipBottomMarginPx: 0,
    contactFontSizePx: 8.2,
    bodyHorizontalPaddingPx: 24,
    bodyVerticalPaddingPx: 20,
    introCardBorderWidthPx: 1,
    introCardRadiusPx: 16,
    introCardHorizontalPaddingPx: 18,
    introCardVerticalPaddingPx: 14,
    introCardBottomMarginPx: 16,
    sectionTitleFontSizePx: 9,
    sectionTitleLetterSpacingPx: 1.15,
    sectionTitleBottomMarginPx: 8,
    paragraphFontSizePx: 9.3,
    leftColumnWidthPercent: 33,
    rightColumnWidthPercent: 67,
    chipGapPx: 6,
    chipBorderWidthPx: 1,
    chipHorizontalPaddingPx: 8,
    chipVerticalPaddingPx: 4,
    chipRightMarginPx: 6,
    chipBottomMarginPx: 6,
    chipFontSizePx: 8.1,
    sectionBottomMarginPx: 16,
    blockBorderWidthPx: 1,
    blockRadiusPx: 14,
    blockHorizontalPaddingPx: 16,
    blockVerticalPaddingPx: 14,
    blockBottomMarginPx: 12,
    roleRowBottomMarginPx: 3,
    roleTitleFontSizePx: 11.1,
    roleMetaFontSizePx: 8.2,
    roleMetaTopMarginPx: 2,
    roleMetaLetterSpacingPx: 0.4,
    companyFontSizePx: 9.2,
    companyTopMarginPx: 2,
    bulletTopMarginPx: 5,
    bulletRowBottomMarginPx: 4,
    bulletWidthPx: 9,
    bulletFontSizePx: 9,
    bulletPaddingTopPx: 0.5,
    bulletTextFontSizePx: 9.1,
    educationItemBottomMarginPx: 10,
    educationTitleFontSizePx: 9.6,
    educationMetaFontSizePx: 8.15,
    educationMetaTopMarginPx: 2,
  },
} as const;
