export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  NEW_DOCUMENT: "/new-document",
  DOCUMENTS: "/documents",
  RESUME: "/documents/resume",
  COVER_LETTER: "/documents/cover-letter",
  PRICING: "/pricing",
  SETTINGS: "/settings",
};
